{% set name = "protlearn" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 093fecebecd98da885b6d76588d510b42c15dfa65384ac52ebdc95d80ce4f1f8
build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - scikit-learn
    - xgboost
    - mlxtend
    - biopython

test:
  requires:
    - python {{ python_min }}
  imports:
    - protlearn
    - protlearn.dimreduction

about:
  home: https://github.com/tadorfer/protlearn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for extracting protein sequence features

  doc_url: https://protlearn.readthedocs.io/en/latest/
  dev_url: https://github.com/tadorfer/protlearn

extra:
  recipe-maintainers:
    - tadorfer
